### ISSUE TITLE
[feature request] Expose serial from ATECC608A

### ISSUE THREAD

**Issue by jfbus** [sfera-labs/exo-sense-pi-kernel-module#1]
Hi !

It would be nice to be able to get the serial from the ATECC608A using /sys/class.

Thanks

**Comment by bancha321** [comment]
Hi jfbus,
thank you for the valuable suggestion. We strongly agree with you, and we're taking in charge your request.

**Comment by jfbus** [comment]
Great ! Thanks.

**Comment by bancha321** [comment]
Hi Jean-François,
the ATEC serial number exposure's been implemented and merged into the master branch, you can test it too. 

The serial number of the secure element is read from file /sys/class/exosensepi/sec_elem/serial_num. 
Here's an example from my device:
pi@raspberrypi:/usr/local/bin $ more /sys/class/exosensepi/sec_elem/serial_num 
01 23 AA 7B C8 AB EA F5 EE 

If you're satisfied with the result, please close this thread
Thank you

**Comment by jfbus** [comment]
Hi, Great !

Just a question : why add spaces ? Keeping a pure hex without spaces makes it easier to reuse.

**Comment by bancha321** [comment]
I disagree with you. I chose this form of representation because we think it's a good way to represent the serial number. I could have used other forms like "0x01 0x23 0xAA 0x7B 0xC8 0xAB 0xEA 0xF5 0xEE" or "01:23:AA:7B:C8:AB:EA:F5:EE", all of them contains the correct info about the serial number, but none of them is the best suited representation for all existing necessities. Just making some analogy, the symbols of house in Simplified Chinese and Traditional Chinese both means house, but they are graphically different, does this mean that one is wrong, or better, or more suited for reuse? The real fact is that the Simplified Chinese is easier for people in mainland China, while Traditional Chinese is easier to use for people in Taiwan.
Coming back to our case, what happens if I want to separate the serial number in single bytes using a space separator and then take only the variable part of the serial number for my personal purposes? In that case I may think that the actual representation is more easier to be reused, in contrast with your thinking.
My concern is only about the correctness of the serial number, how I represent it can't be the best solution for everybody, universally speaking

**Comment by bancha321** [comment]
p.s. sorry i clicked the "close issue" button by mistake. I just reopened it right after

**Comment by bancha321** [comment]
p.p.s. I forgot to thank you for your valuable suggestion. I didn't mean to be rude but I closed the message by mistake and I didn't even have time to make a proper closure. I just wanted to show you my opinion, which can be right or wrong, depending from the point of view. If you need more clarification about the secure element, I'll be happy to help you, if I am able to.
Thank you again
Regards

**Comment by jfbus** [comment]
No worries. Thanks for adding the feature.

Having spaces is not a major issue. As I prefer the serial without spaces (more compact, easier to parse to binary, no need to escape in urls or filenames), I'll clean them, but I understand you would choose to have spaces.
