### ISSUE TITLE
[feature request] add per-octave band sound levels

### ISSUE THREAD

**Issue by jfbus** [sfera-labs/exo-sense-pi-kernel-module#9]
The new sound processing is great.

Would it be possible to have per octave band sound levels (using the same weightings as the other sound measurements) ?

I don't think interval measurements are needed.

This could be implemented as:
```
cat /sys/class/exosensepi/sound_eval/octave_period
[dBA/Z/C for the 31.5Hz band] [63 Hz] [...] [16kHz]
```

References:
* https://en.wikipedia.org/wiki/Octave_band
* https://www.cirrusresearch.co.uk/blog/2020/03/calculation-of-dba-from-octave-band-sound-pressure-levels/

**Comment by bancha321** [comment]
The actual utility is evaluating in 1/3 octave bands, because it has a more detailed frequency filtering table, but it's possible to achieve what you ask with small changes.

I will modify the utility to evaluate/output in 1/3 octave or in 1 octave bands, accordingly to the value inside a parameter file. 

In conclusion, to satisfy your request, 2 files are going to be added inside folder /sys/class/exosensepi/sound_eval/:
One file for parameter selection between 1/3 octave and 1/octave frequency filtering/period result output
One additional file will be added for the period results of each bandwidth interval, containing values of sound levels for each frequency bandwidth and a timestamp at the end.

**Comment by bancha321** [comment]
Feature implemented in exo-sense-pi-kernel-module from version 2.0
